import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sports n stuff",
  description: "Generated by create next app and Gage",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="bg-gray-200 max-w-screen-2xl mx-auto min-h-screen text-black flex justify-center">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
